version: 2

build:
  os: "ubuntu-20.04"
  tools:
    python: "mambaforge-4.10"

conda:
  environment:
    name: fecsep
    channels:
      - conda-forge
      - defaults
    dependencies:
      - pycsep
python:
  - requirements: docs/requirements_dev.txt
  - method: pip
