name: fecsep
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.8
  - numpy=1.22.0
  - cartopy
  - geos
  - pycsep
  - pyproj
  - pyshp
  - shapely
  - pandas
  - scipy
  - matplotlib
  - obspy
  - mercantile