name: floatcsep
channels:
    - conda-forge
    - defaults
dependencies:
    - numpy==1.23.4
    - pycsep==0.6.1
    - dateparser
    - docker-py
    - flake8
    - gitpython
    - h5py
    - matplotlib
    - pip
    - pyshp
    - pyyaml
    - requests
    - seaborn
    - tables
    - pytables
    - xmltodict
