name: gefe
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pycsep=0.6.0
  - cartopy=0.20.2
  - geos=3.10.2
  - matplotlib-base=3.5.1
  - mercantile=1.2.1
  - numpy=1.21.5
  - obspy=1.2.2
  - pandas=1.4.1
  - pyproj=3.3.0
  - pyshp=2.2.0
  - scipy=1.8.0
  - shapely=1.8.0
