name: floatcsep
channels:
    - conda-forge
    - defaults
dependencies:
    - numpy
    - pycsep
    - cartopy
    - dateparser
    - flake8
    - geos
    - gitpython
    - h5py
    - matplotlib
    - mercantile
    - mypy
    - obspy
    - pandas
    - pillow
    - pyproj
    - pyshp
    - pytest-cov
    - pytest
    - pyyaml
    - requests
    - scipy
    - seaborn
    - shapely
    - sphinx
    - sphinx-autoapi
    - sphinx-gallery
    - sphinx-rtd-theme
    - pytables
    - tox
    - vcrpy
    - xmltodict
