name: floatcsep
channels:
    - conda-forge
    - defaults
dependencies:
    - numpy
    - pycsep
    - dateparser
    - docker-py
    - flake8
    - gitpython
    - h5py
    - matplotlib
    - pip
    - pyshp
    - pyyaml
    - requests
    - seaborn
    - sphinx
    - sphinx-autoapi
    - sphinx-gallery
    - sphinx-rtd-theme
    - pytables
    - xmltodict
