name: tests

on:
  push:
    branches-ignore:
    - 'v*'
  pull_request:

jobs:
  build:
    if: github.repository == 'cseptesting/fecsep'
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: ['3.10']
    defaults:
      run:
        shell: bash -l {0}

    steps:
    - uses: actions/checkout@v2
    - uses: conda-incubator/setup-miniconda@v2
      with:
        python-version: ${{ matrix.python-version }}
        activate-environment: fecsep-dev
        channels: conda-forge

    - name: Install conda dependencies
      run: |
        PACKAGES="$PACKAGES numpy geos cartopy pycsep"
        conda install $PACKAGES
        conda info -a
        conda list

    - name: Install pip dependencies
      run: |
        pip install -r requirements_dev.txt

    - name: Install feCSEP
      run: |
        pip install --no-deps -e .
        python -c "import fecsep; print('Version: ', fecsep.__version__)"

    - name: Test with pytest
      run: |
        pytest --cov=./ --cov-config=.coveragerc

    - name: Upload coverage
      if: matrix.os == 'ubuntu-latest' && matrix.python-version == '3.10'
      run: |
        bash <(curl -s https://codecov.io/bash) || echo 'Codecov failed to upload'
