name: build-docs

on:
  pull_request:
    branches: [ main ]

jobs:
  build_docs:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: '3.10'
          activate-environment: fecsep-dev
          channels: conda-forge

      - name: Install dependencies
        run: |
          conda env update --file environment.yml
          conda info -a
          conda list

      - name: Install feCSEP
        run: |
          pip install --no-deps -e .
          python -c "import fecsep; print('Version: ', fecsep.__version__)"

      - name: Build documentation
        run: |
          make -C docs clean
          make -C docs html