name: docs

on:
  push:
    branches-ignore:
      - 'v*'
  pull_request:
    branches: [ main ]

jobs:
  build_docs:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: '3.10'
          activate-environment: fecsep-dev
          channels: conda-forge

      - name: Install conda dependencies
        run: |
          PACKAGES="$PACKAGES numpy==1.23.4 geos cartopy pycsep"
          conda install $PACKAGES
          conda info -a
          conda list

      - name: Install pip dependencies
        run: |
          pip install -r requirements_dev.txt

      - name: Install feCSEP
        run: |
          pip install --no-deps -e .
          python -c "import fecsep; print('Version: ', fecsep.__version__)"

      - name: Build documentation
        run: |
          make -C docs clean
          make -C docs html